[versions]
kotlin = "1.5.10"
compose = "1.0.0"
ktlint = "0.41.0"
room = "2.4.0-alpha04"
dagger = "2.38.1"
androidxhilt = "1.0.0"

[libraries]
android-gradlePlugin = "com.android.tools.build:gradle:7.1.0-alpha05"

kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-coreKtx = { group = "androidx.core", name = "core-ktx", version = "1.6.0" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.3.1" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.3.0-rc02" }

androidx-room-common = { module = "androidx.room:room-common", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxhilt" }

androidx-hilt-navigationCompose = "androidx.hilt:hilt-navigation-compose:1.0.0-alpha03"

androidx-navigation-compose = "androidx.navigation:navigation-compose:2.4.0-alpha05"

compose-ui-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-material-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-animation-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }

google-android-material-material = { group = "com.google.android.material", name = "material", version = "1.4.0" }

android-tools-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version = "1.1.5" }

dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
dagger-hilt-gradlePlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }