[versions]
kotlin = "1.5.21"
compose = "1.0.1"
ktlint = "0.41.0"
room = "2.4.0-alpha04"
dagger = "2.38.1"
androidxhilt = "1.0.0"
androidxlifecycle = "2.4.0-alpha03"
kotlinxcoroutines = "1.5.1"
mockk = "1.12.0"

[libraries]
android-gp = "com.android.tools.build:gradle:7.1.0-alpha11"

kotlin-gp = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-coreKtx = { group = "androidx.core", name = "core-ktx", version = "1.6.0" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.3.1" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.3.0-rc02" }

androidx-room-common = { module = "androidx.room:room-common", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxlifecycle" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidxlifecycle" }

androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxhilt" }

androidx-hilt-navigationCompose = "androidx.hilt:hilt-navigation-compose:1.0.0-alpha03"

androidx-navigation-compose = "androidx.navigation:navigation-compose:2.4.0-alpha05"

compose-ui-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-material-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-animation-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }

google-android-material-material = { group = "com.google.android.material", name = "material", version = "1.4.0" }

android-tools-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version = "1.1.5" }

dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
dagger-hilt-gp = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxcoroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxcoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxcoroutines" }

truth = "com.google.truth:truth:1.1.3"

junit4 = "junit:junit:4.13.2"

robolectric = "org.robolectric:robolectric:4.6.1"

androidx-test-core = "androidx.test:core:1.3.0"
androidx-test-runner = "androidx.test:runner:1.1.0"
androidx-test-rules = "androidx.test:rules:1.1.0"
androidx-test-ext-junit = "androidx.test.ext:junit:1.1.2"
androidx-test-ext-truth = "androidx.test.ext:truth:1.0.0"

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

turbine = "app.cash.turbine:turbine:0.6.1"

androidx-arch-core-testing = "androidx.arch.core:core-testing:2.1.0"