[versions]
compose = "1.0.0-rc02"
ktlint = "0.41.0"

[libraries]
androidx-coreKtx = { group = "androidx.core", name = "core-ktx", version = "1.3.2" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.2.0" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.3.0-rc02" }

compose-ui-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-material-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }

google-android-material-material = { group = "com.google.android.material", name = "material", version = "1.3.0" }